services:
  api:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    command: npm run start

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ponchouser
      POSTGRES_PASSWORD: ponchopass
      POSTGRES_DB: ponchopay_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ponchouser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
